# GirlTREK Dashboard Data Entry App Configuration
# This file should be placed in the .streamlit folder

# GitHub configuration
github_token = "your-github-personal-access-token-here"

# Database connection for optional SQL storage
[
connections.dashboard_db
]
type = "sqlite"
url = "sqlite:///data/dashboard.db"

# Additional app configuration
[
app
]
org_name = "GirlTREK"
environment = "development"  # Change to "production" for deploymen
